	[[module.entry]]
	name = "MICSEL"
	uuid = "32FE92C1-1E17-4FC2-9758-C7F3542E980A"
	affinity_mask = "0x1"
	instance_count = "8"
	domain_types = "0"
	load_type = "0"
	init_config = "1"
	module_type = "0xC"
	auto_start = "0"
	sched_caps = [1, 0x00008000]

	REM # pin = [dir, type, sample rate, size, container, channel-cfg]
	pin = [0, 0, 0xfeef, 0xe, 0xa, 0x45ff, 1, 0, 0xfeef, 0xe, 0xa, 0x45ff]

	REM # mod_cfg [PAR_0 PAR_1 PAR_2 PAR_3 IS_BYTES CPS IBS OBS MOD_FLAGS CPC OBLS]
	mod_cfg = [0, 0, 0, 0, 960, 488500, 16, 16, 0, 0, 0,
			1, 0, 0, 0, 960, 964500, 16, 16, 0, 0, 0,
			2, 0, 0, 0, 960, 2003000, 16, 16, 0, 0, 0]

	index = __COUNTER__
