 	[[module.entry]]
	name = "MUX"
	uuid = "64ce6e35-857a-4878-ace8-e2a2f42e3069"
	affinity_mask = "0x1"
	instance_count = "15"
	domain_types = "0"
	load_type = "0"
	module_type = "6"
	auto_start = "0"
	sched_caps = [1, 0x00008000]

	REM # pin = [dir, type, sample rate, size, container, channel-cfg]
	pin = [0, 0, 0xfeef, 0xf, 0xa, 0x45ff,
			0, 0, 0xfeef, 0xf, 0xa, 0x45ff,
			1, 0, 0xfeef, 0xf, 0xa, 0x45ff]

	REM # mod_cfg [PAR_0 PAR_1 PAR_2 PAR_3 IS_BYTES CPS IBS OBS MOD_FLAGS CPC OBLS]
	mod_cfg = [0, 0, 0, 0, 280, 460700, 16, 16, 0, 0, 0]

	index = __COUNTER__
